# Practical_6: Numpy

In [ ]:
---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

In [2]:
import numpy as np
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```
---

In [22]:
A=np.zeros((3,3),dtype=int) # the zeros are integer
print(A)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


np.zeros((3,3))

In [ ]:
### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [ ]:
---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python

In [39]:

A=np.identity(5,dtype=int)
print(A)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [26]:
import numpy as np
A=np.random.seed(10)
A

In [ ]:
# Exercise 4
```

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [41]:
A=np.random.random((4,4))
print(A)

[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]]


In [ ]:
### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

In [42]:
A=np.random.random((4,4))
print(A.shape)

(4, 4)


In [ ]:
### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [56]:
A=np.arange(1,10)
print(A)
p=A.reshape((3,3))
print(p)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

In [57]:
A=np.random.random((4,4))
print(A.dtype)

float64


In [ ]:
### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

In [28]:
A=np.arange(2,101,2)
print(A)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

In [76]:
A=np.random.randint(10,51,(6,6))
print(A)
print(np.sum(A)) # it gives the sum of all elements in the array

[[11 28 44 21 20 46]
 [16 13 44 31 26 49]
 [28 31 33 29 17 26]
 [13 48 37 42 33 44]
 [35 26 28 29 42 34]
 [50 18 32 21 18 34]]
1097


In [ ]:
### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

In [85]:
A=np.random.randint(1,5,(2,2))
print(A)
print(A[1,:])

[[4 3]
 [1 1]]
[1 1]


In [ ]:
### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

In [74]:
A=np.arange(16)
print(A)
print(sum(A))
print(np.sum(A))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
120
120


In [70]:
sum(np.arange(16))


120

In [ ]:
### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [114]:
A=np.arange(1,4)
print(A)
print(np.mean(A))
# another method
print(np.mean(np.arange(1,4)))
print(np.median(np.arange(1,4)))
print(np.std(np.arange(1,4)))

[1 2 3]
2.0
2.0
2.0
0.816496580927726


In [ ]:
### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [115]:
print(np.max(np.arange(1,16)))
print(np.min(np.arange(1,16)))

15
1


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [130]:
import numpy as np
A= np.random.randint(1, 16,20)
print(A)
print(np.argmax(A))



[ 3  6 15 13  1 13  5  3 10  9  6  3  7 15  4  8  7  6  9 14]
2


In [ ]:
### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [143]:
A=np.arange(0,10)
print(A)
print(A[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [ ]:
---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [6]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[2,4,6],[8,10,12],[14,16,18]])
print(A*B)


[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]


In [ ]:
---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

In [13]:
import numpy as np
A=np.array([2,4,6])
print(np.diag(A))

[[2 0 0]
 [0 4 0]
 [0 0 6]]


In [20]:
print(np.array([[1,2],[3,4],[5,6]]))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

In [22]:
print(np.dot(np.array([[1,2,3],[4,5,5]]),np.array([[1,2],[3,4],[5,6]])))

[[22 28]
 [44 58]]


In [ ]:
### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

In [24]:
print(np.dot(np.array([[2,3],[4,2]]),np.array([[1,2],[4,1]])))

[[14  7]
 [12 10]]


In [ ]:
### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

In [29]:
print(np.vstack((np.array([[1,2,3],[4,5,6]]), np.array([[7,8,9]]))))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

In [44]:
import numpy as np
print(np.hstack((np.array([[1, 2, 3], [4, 5, 6]]), np.array([[7, 8], [9, 10]]))))

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [ ]:
### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

In [49]:
print(np.split(np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]), 3))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [ ]:
### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

In [ ]:
### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

In [ ]:
### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

In [ ]:
### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

In [ ]:
### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

In [ ]:
### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

In [ ]:
### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

In [ ]:
### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---